name: cd

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy
    runs-on: [self-hosted, X64, Windows ,win]

    steps:
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
        shell: cmd

      - name: Push to Artifact Registry
        run: docker push us-central1-docker.pkg.dev/oceanic-column-484505-s1/notely-ar-repo/trial-pyth/notely:latest
        shell: cmd
