name: ci

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: wsl

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Tests
        run: go test -cover ./...

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Gosec
        run: gosec ./...
      
  style:
    name: Style
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Style
        run: test -z $(go fmt ./...)

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
